[build]
  image = "directus/directus:latest"

[env]
  STORAGE_LOCAL_ROOT = "/data"
  STORAGE_LOCATIONS = "local"

[mounts]
  source = "directus_data"
  destination = "/data"

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[checks]
  [checks.admin]
    port = 8055
    type = "http"
    interval = "5s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/admin"